### ISSUE TITLE
[PE-D][Tester A] Lack of feedback to user

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S2-CS2113-T15-1/tp#128]
![image.png](https://raw.githubusercontent.com/BenjoBurger/ped/main/files/e710350b-aa12-40a7-b5a7-8e6e0bea6d0b.png)

It is very hard to understand what my commands are doing. Would like to see some line breaks or some type of message when I successfully entered a command.

-------------
Labels: `type.FeatureFlaw` `severity.Medium`
original: BenjoBurger/ped#1

**Comment by 1simjustin** [comment]
To add feedback message prompts and add line breaks between command calls
