### ISSUE TITLE
[PE-D][Tester B] Edit member feature not working

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S2-CS2113-T15-1/tp#134]
As per UG,

1. I listed all members. Alice is found
2. Tried to edit her name but it says invalid index.

![image.png](https://raw.githubusercontent.com/EdmundTangg/ped/main/files/14763bd4-6535-45a0-92b2-584c81d897f8.png)

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: EdmundTangg/ped#5

**Comment by 1simjustin** [comment]
Closed as repeated
