### ISSUE TITLE
[PE-D][Tester C] Find transactions: List transactions index failure

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S2-CS2113-T15-1/tp#138]
1. Screenshot of "List transactions"

![image.png](https://raw.githubusercontent.com/jasraa/ped/main/files/f4dcbd84-3758-4a91-ab75-56a751ae5607.png)

2. Screenshot of "Find transactions Alice"

![image.png](https://raw.githubusercontent.com/jasraa/ped/main/files/3c722041-0038-4eae-8a83-fa03e917f9df.png)
The transaction index is not listed correctly

3. UG clearly mentions that each transaction is indexed for easy reference

![image.png](https://raw.githubusercontent.com/jasraa/ped/main/files/cea768bd-5d33-41f5-80da-ba2c29e3b0c6.png)

-------------
Labels: `type.FeatureFlaw` `severity.Medium`
original: jasraa/ped#3

**Comment by FeathersRe** [comment]
Feels like this issue can be instead resolved by updating the UG! The transaction indexes were originally introduced to better keep track of the <b>number</b> of transactions under the interested person, not really a fix ID to search for a transaction.

**Comment by FeathersRe** [comment]
After re-inspection of the code, this should be an easy fix on the functionality level also. Going with this convention!
