### ISSUE TITLE
Improve UI

### ISSUE THREAD

**Issue by 1simjustin** [AY2324S2-CS2113-T15-1/tp#50]
General improvements to UI for better readability.
Add ASCII art to make the UI look better.

**Comment by jing-xiang** [comment]
nit:

![image](https://github.com/AY2324S2-CS2113-T15-1/tp/assets/61624545/dcf9a10c-cb3a-4278-ae45-ef04f3c48463)

Can change 'owes' to 'transfers'

![image](https://github.com/AY2324S2-CS2113-T15-1/tp/assets/61624545/4b0273f0-a4da-4df9-878f-885f88ac3abd)
Can change 'owns' to 'is involved in'

**Comment by jing-xiang** [comment]
The following commands: list transactions and find transactions do not have dollar signs, but the other commands have dollar signs.

Add in the dollar sign for consistency.

![image](https://github.com/AY2324S2-CS2113-T15-1/tp/assets/61624545/a5713abb-459b-4972-819e-09464c9551e4)

**Comment by jing-xiang** [comment]
![image](https://github.com/AY2324S2-CS2113-T15-1/tp/assets/61624545/f0686bb6-271b-4c1c-96e3-2e6f43f1ad02)


it's not fixed, can we PR for this ASAP?
